_PATH = r'(?:(?:"(?P<quotedPath>[^"]+)")|(?P<path>[^\s"]+))'

_TYPE_NUMBER = "(?P<type>[0-9]+)"

_TYPE_NUMBERS = "(?P<type>(?i:type)[0-9]+)(?P<moreTypes>(, (?i:type)[0-9]+)+)?"


TYPES_FOUND = rf"""\*\*\* Notice at time        :         0\.000000
    Generated by Unit     : Not applicable or not available
    Generated by Type     : Not applicable or not available
    Message               : The following Types were loaded from {_PATH}: {_TYPE_NUMBERS}
"""


DUPLICATE_FOUND = rf"""\*\*\* Warning at time       :         0\.000000
    Generated by Unit     : Not applicable or not available
    Generated by Type     : [\s]*{_TYPE_NUMBER}
    TRNSYS Message    200 : This TYPE was found in more than one DLL\. The first instance of the TYPE was loaded\. Subsequent instances have been ignored
    Reported information  : A duplicate of (?i:type)[0-9]+ was found in {_PATH}
"""

TYPE_NOT_FOUND = rf"""\*\*\* Fatal Error at time   :         0\.000000
    Generated by Unit     : Not applicable or not available
    Generated by Type     : [\s]*{_TYPE_NUMBER}
    TRNSYS Message    105 : A TYPE was called in the TRNSYS input file but was either not linked into trndll\.dll or was not found in an external dll\. A dummy subroutine was called in its place\. Please link the TYPE or remove it from the input file
    Reported information  : [\s]*(?i:type)[0-9]+ could not be located in either the trndll\.dll or in an external dll\. Please relink theTRNDll\.dll including this Type or make sure that an external DLL in the \\UserLib\\DebugDLLs and \\UserLib\\ReleaseDLLs folders contain the Type\.
 """
