import trnsysGUI.imageAccessor as _ia

ImageAccessor = _ia.ImageAccessorBase
SvgImageAccessor = _ia.SvgImageAccessor

AIR_SOURCE_HP_SVG = _ia.createForPackageResource(_ia.SvgImageAccessor, "images/AirSourceHP.svg")
BOILER_SVG = _ia.createForPackageResource(_ia.SvgImageAccessor, "images/Boiler.svg")
CENTRAL_RECEVIER_SVG = _ia.createForPackageResource(_ia.SvgImageAccessor, "images/CentralReceiver.svg")
COLLECTOR_SVG = _ia.createForPackageResource(_ia.SvgImageAccessor, "images/Collector.svg")
CONNECTOR_SVG = _ia.createForPackageResource(_ia.SvgImageAccessor, "images/Connector.svg")
ELECTRIC_ROD_SVG = _ia.createForPackageResource(_ia.SvgImageAccessor, "images/ElectricRod.svg")
EXPORT_DCK_PNG = _ia.createForPackageResource(_ia.PngImageAccessor, "images/exportDck.png")
EXPORT_DCK_SVG = _ia.createForPackageResource(_ia.SvgImageAccessor, "images/exportDck.svg")
EXPORT_HYDRAULIC_CONTROL_PNG = _ia.createForPackageResource(_ia.PngImageAccessor, "images/exportHydraulicControl.png")
EXPORT_HYDRAULIC_CONTROL_SVG = _ia.createForPackageResource(_ia.SvgImageAccessor, "images/exportHydraulicControl.svg")
EXPORT_HYDRAULICS_PNG = _ia.createForPackageResource(_ia.PngImageAccessor, "images/exportHydraulics.png")
EXPORT_HYDRAULICS_SVG = _ia.createForPackageResource(_ia.SvgImageAccessor, "images/exportHydraulics.svg")
EXTERNAL_HX_SVG = _ia.createForPackageResource(_ia.SvgImageAccessor, "images/ExternalHx.svg")
GEAR_PNG = _ia.createForPackageResource(_ia.PngImageAccessor, "images/gear.png")
GEAR_SVG = _ia.createForPackageResource(_ia.SvgImageAccessor, "images/gear.svg")
GENERIC_BLOCK_PNG = _ia.createForPackageResource(_ia.PngImageAccessor, "images/GenericBlock.png")
GENERIC_ITEM_PNG = _ia.createForPackageResource(_ia.PngImageAccessor, "images/GenericItem.png")
GROUND_SOURCE_HX_SVG = _ia.createForPackageResource(_ia.SvgImageAccessor, "images/GroundSourceHx.svg")
HP_SVG = _ia.createForPackageResource(_ia.SvgImageAccessor, "images/HP.svg")
HP_DOUBLE_DUAL_SVG = _ia.createForPackageResource(_ia.SvgImageAccessor, "images/HPDoubleDual.svg")
HP_DUAL_SVG = _ia.createForPackageResource(_ia.SvgImageAccessor, "images/HPDualSourceSingleSink.svg")
HP_TWO_HX_SVG = _ia.createForPackageResource(_ia.SvgImageAccessor, "images/HPTwoHx.svg")
ICE_STORAGE_SVG = _ia.createForPackageResource(_ia.SvgImageAccessor, "images/IceStorage.svg")
ICE_STORAGE_TWO_HX_SVG = _ia.createForPackageResource(_ia.SvgImageAccessor, "images/IceStorageTwoHx.svg")
INBOX_PNG = _ia.createForPackageResource(_ia.PngImageAccessor, "images/inbox.png")
LABEL_TOGGLE_PNG = _ia.createForPackageResource(_ia.PngImageAccessor, "images/labelToggle.png")
OUTBOX_PNG = _ia.createForPackageResource(_ia.PngImageAccessor, "images/outbox.png")
PIT_STORAGE_SVG = _ia.createForPackageResource(_ia.SvgImageAccessor, "images/PitStorage.svg")
PROCESS_SIMULATION_PNG = _ia.createForPackageResource(_ia.PngImageAccessor, "images/processSimulation.png")
PROCESS_SIMULATION_SVG = _ia.createForPackageResource(_ia.SvgImageAccessor, "images/processSimulation.svg")
PT_FIELD_SVG = _ia.createForPackageResource(_ia.SvgImageAccessor, "images/ParabolicTroughField.svg")
PUMP_SVG = _ia.createForPackageResource(_ia.SvgImageAccessor, "images/Pump.svg")
PV_SVG = _ia.createForPackageResource(_ia.SvgImageAccessor, "images/PV.svg")
RADIATOR_SVG = _ia.createForPackageResource(_ia.SvgImageAccessor, "images/Radiator.svg")
ROTATE_LEFT_PNG = _ia.createForPackageResource(_ia.PngImageAccessor, "images/rotate-left.png")
ROTATE_TO_RIGHT_PNG = _ia.createForPackageResource(_ia.PngImageAccessor, "images/rotate-to-right.png")
RUN_MFS_PNG = _ia.createForPackageResource(_ia.PngImageAccessor, "images/runMfs.png")
RUN_MFS_SVG = _ia.createForPackageResource(_ia.SvgImageAccessor, "images/runMfs.svg")
RUN_SIMULATION_PNG = _ia.createForPackageResource(_ia.PngImageAccessor, "images/runSimulation.png")
RUN_SIMULATION_SVG = _ia.createForPackageResource(_ia.SvgImageAccessor, "images/runSimulation.svg")
SALT_TANK_COLD_SVG = _ia.createForPackageResource(_ia.SvgImageAccessor, "images/SaltTankCold.svg")
SALT_TANK_HOT_SVG = _ia.createForPackageResource(_ia.SvgImageAccessor, "images/SaltTankHot.svg")
STEAM_POWER_BLOCK_SVG = _ia.createForPackageResource(_ia.SvgImageAccessor, "images/powerBlock.svg")
STORAGE_TANK_SVG = _ia.createForPackageResource(_ia.SvgImageAccessor, "images/StorageTank.svg")
TEE_PIECE_SVG = _ia.createForPackageResource(_ia.SvgImageAccessor, "images/TeePiece.svg")
DP_TEE_PIECE_SVG = _ia.createForPackageResource(_ia.SvgImageAccessor, "images/DPTeePiece.svg")
SINGLE_DOUBLE_PIPE_CONNECTOR_SVG = _ia.createForPackageResource(
    _ia.SvgImageAccessor, "images/SingleDoublePipeConnector.svg"
)
DOUBLE_DOUBLE_PIPE_CONNECTOR_SVG = _ia.createForPackageResource(
    _ia.SvgImageAccessor, "images/DoubleDoublePipeConnector.svg"
)
TRASH_PNG = _ia.createForPackageResource(_ia.PngImageAccessor, "images/trash.png")
T_VENTIL_SVG = _ia.createForPackageResource(_ia.SvgImageAccessor, "images/TVentil.svg")
UPDATE_CONFIG_PNG = _ia.createForPackageResource(_ia.PngImageAccessor, "images/updateConfig.png")
UPDATE_CONFIG_SVG = _ia.createForPackageResource(_ia.SvgImageAccessor, "images/updateConfig.svg")
VIS_MFS_PNG = _ia.createForPackageResource(_ia.PngImageAccessor, "images/visMfs.png")
VIS_MFS_SVG = _ia.createForPackageResource(_ia.SvgImageAccessor, "images/visMfs.svg")
TAP_SVG = _ia.createForPackageResource(_ia.SvgImageAccessor, "images/Tap.svg")
TAP_MAINS_SVG = _ia.createForPackageResource(_ia.SvgImageAccessor, "images/TapMains.svg")
SINK_SVG = _ia.createForPackageResource(_ia.SvgImageAccessor, "images/Sink.svg")
SOURCE_SVG = _ia.createForPackageResource(_ia.SvgImageAccessor, "images/Source.svg")
SOURCE_SINK_SVG = _ia.createForPackageResource(_ia.SvgImageAccessor, "images/SourceAndSink.svg")
GEOTHERM_SVG = _ia.createForPackageResource(_ia.SvgImageAccessor, "images/Geotherm.svg")
WATER_SVG = _ia.createForPackageResource(_ia.SvgImageAccessor, "images/Water.svg")
CRYSTALIZER_SVG = _ia.createForPackageResource(_ia.SvgImageAccessor, "images/Crystalizer.svg")
ZOOM_0_PNG = _ia.createForPackageResource(_ia.PngImageAccessor, "images/zoom-0.png")
ZOOM_IN_PNG = _ia.createForPackageResource(_ia.PngImageAccessor, "images/zoom-in.png")
ZOOM_OUT_PNG = _ia.createForPackageResource(_ia.PngImageAccessor, "images/zoom-out.png")
