import trnsysGUI.imageAccessor as _ia

ImageAccessor = _ia.ImageAccessorBase
SvgImageAccessor = _ia.SvgImageAccessor

AIR_SOURCE_HP_SVG = _ia.ImageAccessorBase.createForPackageResource("images/AirSourceHP.svg")
BOILER_SVG = _ia.ImageAccessorBase.createForPackageResource("images/Boiler.svg")
CENTRAL_RECEVIER_SVG = _ia.ImageAccessorBase.createForPackageResource("images/CentralReceiver.svg")
COLLECTOR_SVG = _ia.ImageAccessorBase.createForPackageResource("images/Collector.svg")
CONNECTOR_SVG = _ia.ImageAccessorBase.createForPackageResource("images/Connector.svg")
ELECTRIC_ROD_SVG = _ia.ImageAccessorBase.createForPackageResource("images/ElectricRod.svg")
EXPORT_DCK_PNG = _ia.ImageAccessorBase.createForPackageResource("images/exportDck.png")
EXPORT_DCK_SVG = _ia.ImageAccessorBase.createForPackageResource("images/exportDck.svg")
EXPORT_HYDRAULIC_CONTROL_PNG = _ia.ImageAccessorBase.createForPackageResource("images/exportHydraulicControl.png")
EXPORT_HYDRAULIC_CONTROL_SVG = _ia.ImageAccessorBase.createForPackageResource("images/exportHydraulicControl.svg")
EXPORT_HYDRAULICS_PNG = _ia.ImageAccessorBase.createForPackageResource("images/exportHydraulics.png")
EXPORT_HYDRAULICS_SVG = _ia.ImageAccessorBase.createForPackageResource("images/exportHydraulics.svg")
EXTERNAL_HX_SVG = _ia.ImageAccessorBase.createForPackageResource("images/ExternalHx.svg")
GEAR_PNG = _ia.ImageAccessorBase.createForPackageResource("images/gear.png")
GEAR_SVG = _ia.ImageAccessorBase.createForPackageResource("images/gear.svg")
GENERIC_BLOCK_PNG = _ia.ImageAccessorBase.createForPackageResource("images/GenericBlock.png")
GENERIC_ITEM_PNG = _ia.ImageAccessorBase.createForPackageResource("images/GenericItem.png")
GROUND_SOURCE_HX_SVG = _ia.ImageAccessorBase.createForPackageResource("images/GroundSourceHx.svg")
HP_SVG = _ia.ImageAccessorBase.createForPackageResource("images/HP.svg")
HP_DOUBLE_DUAL_SVG = _ia.ImageAccessorBase.createForPackageResource("images/HPDoubleDual.svg")
HP_DUAL_SVG = _ia.ImageAccessorBase.createForPackageResource("images/HPDualSourceSingleSink.svg")
HP_TWO_HX_SVG = _ia.ImageAccessorBase.createForPackageResource("images/HPTwoHx.svg")
ICE_STORAGE_SVG = _ia.ImageAccessorBase.createForPackageResource("images/IceStorage.svg")
ICE_STORAGE_TWO_HX_SVG = _ia.ImageAccessorBase.createForPackageResource("images/IceStorageTwoHx.svg")
INBOX_PNG = _ia.ImageAccessorBase.createForPackageResource("images/inbox.png")
LABEL_TOGGLE_PNG = _ia.ImageAccessorBase.createForPackageResource("images/labelToggle.png")
OUTBOX_PNG = _ia.ImageAccessorBase.createForPackageResource("images/outbox.png")
PIT_STORAGE_SVG = _ia.ImageAccessorBase.createForPackageResource("images/PitStorage.svg")
PROCESS_SIMULATION_PNG = _ia.ImageAccessorBase.createForPackageResource("images/processSimulation.png")
PROCESS_SIMULATION_SVG = _ia.ImageAccessorBase.createForPackageResource("images/processSimulation.svg")
PT_FIELD_SVG = _ia.ImageAccessorBase.createForPackageResource("images/ParabolicTroughField.svg")
PUMP_SVG = _ia.ImageAccessorBase.createForPackageResource("images/Pump.svg")
PV_SVG = _ia.ImageAccessorBase.createForPackageResource("images/PV.svg")
RADIATOR_SVG = _ia.ImageAccessorBase.createForPackageResource("images/Radiator.svg")
ROTATE_LEFT_PNG = _ia.ImageAccessorBase.createForPackageResource("images/rotate-left.png")
ROTATE_TO_RIGHT_PNG = _ia.ImageAccessorBase.createForPackageResource("images/rotate-to-right.png")
RUN_MFS_PNG = _ia.ImageAccessorBase.createForPackageResource("images/runMfs.png")
RUN_MFS_SVG = _ia.ImageAccessorBase.createForPackageResource("images/runMfs.svg")
RUN_SIMULATION_PNG = _ia.ImageAccessorBase.createForPackageResource("images/runSimulation.png")
RUN_SIMULATION_SVG = _ia.ImageAccessorBase.createForPackageResource("images/runSimulation.svg")
SALT_TANK_COLD_SVG = _ia.ImageAccessorBase.createForPackageResource("images/SaltTankCold.svg")
SALT_TANK_HOT_SVG = _ia.ImageAccessorBase.createForPackageResource("images/SaltTankHot.svg")
STEAM_POWER_BLOCK_SVG = _ia.ImageAccessorBase.createForPackageResource("images/powerBlock.svg")
STORAGE_TANK_SVG = _ia.ImageAccessorBase.createForPackageResource("images/StorageTank.svg")
TEE_PIECE_SVG = _ia.ImageAccessorBase.createForPackageResource("images/TeePiece.svg")
DP_TEE_PIECE_SVG = _ia.ImageAccessorBase.createForPackageResource("images/DPTeePiece.svg")
DP_TEE_PIECE_ROTATED_90 = _ia.ImageAccessorBase.createForPackageResource("images/DPTeePieceRotated90.svg")
DP_TEE_PIECE_ROTATED_180 = _ia.ImageAccessorBase.createForPackageResource("images/DPTeePieceRotated180.svg")
DP_TEE_PIECE_ROTATED_270 = _ia.ImageAccessorBase.createForPackageResource("images/DPTeePieceRotated270.svg")
SINGLE_DOUBLE_PIPE_CONNECTOR_SVG = _ia.ImageAccessorBase.createForPackageResource(
    "images/SingleDoublePipeConnector.svg"
)
DOUBLE_DOUBLE_PIPE_CONNECTOR_SVG = _ia.ImageAccessorBase.createForPackageResource(
    "images/DoubleDoublePipeConnector.svg"
)
TRASH_PNG = _ia.ImageAccessorBase.createForPackageResource("images/trash.png")
T_VENTIL_SVG = _ia.ImageAccessorBase.createForPackageResource("images/TVentil.svg")
UPDATE_CONFIG_PNG = _ia.ImageAccessorBase.createForPackageResource("images/updateConfig.png")
UPDATE_CONFIG_SVG = _ia.ImageAccessorBase.createForPackageResource("images/updateConfig.svg")
VIS_MFS_PNG = _ia.ImageAccessorBase.createForPackageResource("images/visMfs.png")
VIS_MFS_SVG = _ia.ImageAccessorBase.createForPackageResource("images/visMfs.svg")
TAP_SVG = _ia.ImageAccessorBase.createForPackageResource("images/Tap.svg")
TAP_MAINS_SVG = _ia.ImageAccessorBase.createForPackageResource("images/TapMains.svg")
SINK_SVG = _ia.ImageAccessorBase.createForPackageResource("images/Sink.svg")
SOURCE_SVG = _ia.ImageAccessorBase.createForPackageResource("images/Source.svg")
SOURCE_SINK_SVG = _ia.ImageAccessorBase.createForPackageResource("images/SourceAndSink.svg")
GEOTHERM_SVG = _ia.ImageAccessorBase.createForPackageResource("images/Geotherm.svg")
WATER_SVG = _ia.ImageAccessorBase.createForPackageResource("images/Water.svg")
CRYSTALIZER_SVG = _ia.ImageAccessorBase.createForPackageResource("images/Crystalizer.svg")
ZOOM_0_PNG = _ia.ImageAccessorBase.createForPackageResource("images/zoom-0.png")
ZOOM_IN_PNG = _ia.ImageAccessorBase.createForPackageResource("images/zoom-in.png")
ZOOM_OUT_PNG = _ia.ImageAccessorBase.createForPackageResource("images/zoom-out.png")
