name: Static checks and unit tests

on:
  release: 
    branches:
      - '*'
  repository_dispatch:
    types:
      - build-executable-pull-request
      - build-executable-push

jobs:
  build-exe:
    runs-on: [self-hosted, etzel]
    steps:
      - uses: actions/checkout@v3
      - name: Report github.event_name and event_type
        run: |
          echo "Event name: ${{github.event_name}}"
          echo "Event type (via client payload): ${{github.event.client_payload.type}}"
          echo "Event type (via event_type): ${{github.event.event_type}}"
      - name: Build executable
        run: py -3.9 dev-tools/devTools.py -x
      - name: Compute file name
        id: fn
        run: |
          $pytrnsys_gui_sha=$(git rev-parse --short HEAD)
          $pytrnsys_sha=$(release\pyinstaller-venv\Scripts\pip show pytrnsys | Select-String -Pattern "^Version:.*$").Matches.Value.Split(".")[-1].Substring(0,7)
          $ref_name="${{github.ref_name}}".replace("/","-")
          echo "file_name_base=pytrnsys-gui-${ref_name}-${pytrnsys_gui_sha}-${pytrnsys_sha}" >> $env:GITHUB_OUTPUT
      - if: ${{github.event_name == 'release' || (github.event_name == 'repository_dispatch' && github.event.client_payload.type == 'build-executable-push')}}
        name: Create zip file
        run: Compress-Archive -Path data, release\pyinstaller-venv\pytrnsys_data, release\dist -DestinationPath ${{steps.fn.outputs.file_name_base}}.zip
      - if: ${{github.event_name == 'repository_dispatch' && github.event.client_payload.type == 'build-executable-push'}}
        name: Release artifacts (bleeding-edge)
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{secrets.GITHUB_TOKEN}}"
          automatic_release_tag: "bleeding-edge"
          prerelease: true
          title: "Development Build"
          # ATTENTION: `action-automatic-releases` *needs* forward slashes in the paths given to `files`.
          files: ${{steps.fn.outputs.file_name_base}}.zip
      - if: ${{github.event_name == 'release'}}
        name: Release artifacts (${{github.event.release.release_id}})
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{secrets.GITHUB_TOKEN}}"
          title: "Release ${{github.event.release.release_id}}"
          # ATTENTION: `action-automatic-releases` *needs* forward slashes in the paths given to `files`.
          files: ${{steps.fn.outputs.file_name_base}}.zip 
      - if: ${{github.event_name == 'repository_dispatch' && github.event.client_payload.type == 'build-executable-pull-request'}}
        name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{steps.fn.outputs.file_name_base}}
          path: |
            data
            release\pyinstaller-venv\pytrnsys_data
            release\dist
