name: Build executable

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build-executable:
    runs-on: windows-latest
    steps:
      - name: Support longpaths
        run: git config --system core.longpaths true
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Set up venv
        run: |
          python -m venv venv
      - name: Install dependencies
        run: |
          venv\Scripts\python -m pip install --upgrade pip
          venv\Scripts\python -m pip install wheel
          venv\Scripts\pip install -r requirements\release.txt
      - name: Generate UI code from Qt Creator Studio .ui files
        run: |
          venv\Scripts\activate
          python dev-tools\generateGuiClassesFromQtCreatorStudioUiFiles.py
      - name: Build executable
        run: ..\venv\Scripts\pyinstaller pytrnsys-gui.spec
        working-directory: release
      - name: Compute file name
        id: fn
        run: |
          $pytrnsys_gui_sha=(git rev-parse --short HEAD)
          $pytrnsys_sha=(venv\Scripts\pip show pytrnsys | Select-String -Pattern "^Version:.*$").Matches.Value.Split()[-1].Trim()
          $ref_name="${{github.ref_name}}".replace("/","-")
          echo "file_name_base=pytrnsys-gui-${ref_name}-${pytrnsys_gui_sha}-${pytrnsys_sha}" >> $env:GITHUB_OUTPUT
      - name: Create zip file
        run: Compress-Archive -Path data, venv\pytrnsys_data, release\dist\pytrnsys-gui.exe -DestinationPath ${{steps.fn.outputs.file_name_base}}.zip
      - name: Release artifacts
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{secrets.GITHUB_TOKEN}}"
          prerelease: false
          title: "Release build"
          # ATTENTION: `action-automatic-releases` *needs* forward slashes in the paths given to `files`.
          files: ${{steps.fn.outputs.file_name_base}}.zip
