name: Build executable

on:
  workflow_run:
      workflows: ["Publish to PyPI"]
      branches: [v0.10]
      types:
        - completed
  workflow_dispatch:

jobs:
  build-executable:
    runs-on: windows-latest
    steps:
      - name: Support longpaths
        run: git config --system core.longpaths true
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install wheel
          pip install -r requirements\release.txt
      - name: Generate UI code from Qt Creator Studio .ui files
        run: |
          python dev-tools\generateGuiClassesFromQtCreatorStudioUiFiles.py
      - name: Build executable
        run: pyinstaller pytrnsys-gui.spec
        working-directory: release
      - name: Determine output path components
        id: vars
        run: |
          echo "sha_short=$(git rev-parse --short HEAD)" >> $env:GITHUB_OUTPUT
          $ref_name="${{github.ref_name}}".replace("/","-")
          echo "ref_name=$ref_name" >> $env:GITHUB_OUTPUT
      - name: Rename executable
        run: Rename-Item -Path release\dist\pytrnsys-gui.exe -NewName pytrnsys-gui-${{steps.vars.outputs.ref_name}}-${{steps.vars.outputs.sha_short}}.exe
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: pytrnsys-gui-${{steps.vars.outputs.ref_name}}-${{steps.vars.outputs.sha_short}}
          path: release\dist\pytrnsys-gui-${{steps.vars.outputs.ref_name}}-${{steps.vars.outputs.sha_short}}.exe
