name: Build executable

on:
  workflow_dispatch:

jobs:
  build-executable:
    runs-on: windows-latest
    steps:
      - name: Explain
        run: |
          echo "This workflow only exists so that the same workflow on the"
          echo "v0.10 branch can be started by hand."
