name: Release

on:
  release:
    types: [created]

jobs:
  publish-to-pypi:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install wheel
        pip install -r requirements/publish-to-pypi.txt
    - name: Generate UI code from Qt Creator Studio .ui files
      run: python dev-tools/generateGuiClassesFromQtCreatorStudioUiFiles.py
    - name: Build and publish
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        python setup.py sdist bdist_wheel
        twine upload dist/*

  build-executable:
    runs-on: [etzel]
    needs: [publish-to-pypi]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Change to `release` directory
        run: cd release
      - name: Create virtual environment
        run: |
          rmdir /s /q venv
          py -3.9 -m venv venv
      - name: Install dependencies
        run: |
          venv\Scripts\python -m pip install --upgrade pip
          venv\Scripts\python -m pip install wheel
          venv\Scripts\pip install -r requirements\release.txt
      - name: Delete old build artifacts
        run: rmdir /s /q dist build
      - name: Build executable
        run: |
          venv\Scripts\pyinstaller pytrnsys-gui.spec
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: pytrnsys-gui-${{env.GITHUB_REF_NAME}}
          path: dist\pytrnsys-gui
