name: Static checks and unit tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install wheel
        pip install -r requirements/ci/test/requirements.txt
    - name: Static type checking with mypy
      run: |
        mypy trnsysGUI tests dev-tools
      continue-on-error: true
    - name: Lint with pylint
      run: |
        pylint trnsysGUI tests dev-tools
      continue-on-error: true
    - name: Test with pytest
      run: >
        pytest
        --cov=trnsysGUI --cov-report html:test-results/coverage --cov-report term
        --html=test-results/report/report.html
        -m "not manual"
        tests
    - name: Upload test results and coverage reports
      uses: actions/upload-artifact@v2
      with:
        name: test-results-and-coverage-report
        path: test-results
      # Use always() to always run this step to publish test results when there are test failures
      if: ${{ always() }}