name: Static checks and unit tests

on:
  push:
    branches: [ v0.10 ]
  pull_request:
    branches: [ v0.10 ]

jobs:
  build-srspf01:

    runs-on: [self-hosted, srspf01]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install wheel
          pip install -r requirements/test.txt
      - name: Generate UI code from Qt Creator Studio .ui files
        run: python dev-tools/generateGuiClassesFromQtCreatorStudioUiFiles.py
      - name: Static type checking with mypy
        run: python dev-tools/runStaticChecksAndUnitTests.py --type
      - name: Lint with pylint
        run: python dev-tools/runStaticChecksAndUnitTests.py --lint --keep-results
      - name: Generate class and package diagrams
        run: python dev-tools/runStaticChecksAndUnitTests.py --diagram=dot --keep-results
      - name: Test with pytest
        run: python dev-tools/runStaticChecksAndUnitTests.py --unit "linux or linux_ci" --keep-results
      - name: Upload test results and coverage reports
        uses: actions/upload-artifact@v3
        with:
          name: test-results-and-coverage-report-srspf01
          path: test-results
        # Use always() to always run this step to publish test results when there are test failures
        if: ${{ always() }}
